const PointOfInterestList = [
   {
      "id": "banks-and-atm",
      "name": "Banks & ATMs",
      "childrens": [
         "Allahabad Bank",
         "Axis Bank",
         "Bank of India",
         "BankBazaar",
         "Citibank",
         "HDFC",
         "ICICI Bank",
         "Kotak",
         "Standard Chartered",
         "Union Bank of India",
         "Western Union",
         "Yes Bank"
      ]
   },
   {
      "id": "books-and-cinema",
      "name": "Books & Cinema",
      "childrens": [
         "Archies",
         "Big Cinemas",
         "Cinépolis",
         "Crossword",
         "Early Learning Center",
         "Fun Cinemas",
         "Hallmark",
         "Inox Movies",
         "Landmark",
         "OM Bookshop",
         "PVR Cinemas",
         "Reynolds",
         "William Penn"
      ]
   },
   {
      "id": "clothes-shoes-accessories",
      "name": "Clothes, shoes & accessories",
      "childrens": [
         "109 F",
         "AM:PM",
         "Abujani Sandeepkhosla",
         "Accessorize",
         "Alberto Torresi",
         "Alcott",
         "Aldo",
         "All Plus Size Store",
         "Allen Solly",
         "American Tourister",
         "And India",
         "Anju Modi",
         "AnneBra",
         "Arrow",
         "Ashish N Soni",
         "Aswera",
         "BWitch",
         "Baggit",
         "Bagzone",
         "Bally",
         "Balujas",
         "Bata",
         "Bebe",
         "Being Human",
         "Beverly Hills Polo Club",
         "Biba",
         "Blackberrys",
         "Boggi Milano",
         "Bombay Selections",
         "Bossini",
         "Bottega Veneta",
         "Brooks Brothers",
         "Calonge",
         "Canali",
         "Cantabil",
         "Carlton London",
         "Caterpillar footwear",
         "Celio",
         "Charles & Keith",
         "Chemistry",
         "Chhabra 555",
         "Christian Louboutin",
         "Chumbak",
         "Claire's",
         "Clarks",
         "ClubFox",
         "Color Plus",
         "Corneliani",
         "Cotton County",
         "Cottons by Century",
         "Cottonworld",
         "Crocs",
         "Da Milano",
         "Daniel Hechter",
         "Davidoff",
         "Decathlon",
         "Denizen",
         "Derby Jeans",
         "Derhy",
         "Desi Belle",
         "Diesel",
         "Duke",
         "Elle",
         "Emilio Pucci",
         "Enamor",
         "Ensemble",
         "Ermenegildo Zegna",
         "Esbeda",
         "Esprit",
         "Fabindia",
         "Falguni and Shane Peacock",
         "Fastrack",
         "Fbb",
         "Femella",
         "Fendi",
         "Flying Machine",
         "Forever 21",
         "Forever New",
         "Franco Leone",
         "French Connection",
         "GANT",
         "Gas",
         "GauravGupta",
         "Giordano",
         "Giorgio Armani",
         "Givo",
         "Global Desi",
         "Globus",
         "Guess",
         "H&M",
         "Hackett",
         "Happy Socks",
         "Havaianas",
         "Heel and Buckle",
         "Hermès",
         "Hidesign",
         "Holii",
         "Hugo Boss",
         "Hush Puppies",
         "Inc 5",
         "Indian Terrain",
         "Indigo Nation",
         "Jack & Jones",
         "Janavi",
         "Jashn",
         "Jockey",
         "John Players",
         "Judith Leiber",
         "Karmik",
         "Kazo",
         "Khadims",
         "Killer Jeans",
         "Kimaya",
         "Kotwara",
         "La Lingerie",
         "La Senza",
         "LaVen Fashions",
         "Lacoste",
         "Lakshita",
         "Latin Quarters",
         "Lavie",
         "Lee",
         "Levi's",
         "Liberty Shoes",
         "Lifestyle",
         "Louis Philippe",
         "Louis Vuitton",
         "Lovable India",
         "M&B Footwear",
         "Madame",
         "Mango",
         "Manyavar",
         "Marks & Spencer",
         "Max",
         "Meena Bazaar",
         "Metro Shoes",
         "Millionaire",
         "Ministry of Fashion",
         "Mochi",
         "Monte Carlo",
         "Mufti",
         "Mustard",
         "NYCITI",
         "Nautica",
         "Next",
         "Nine West",
         "Numero Uno",
         "Octave",
         "Only",
         "Oxemberg",
         "Pantaloons",
         "Park Avenue",
         "Parx",
         "Paul & Shark",
         "Pavers England",
         "Penny Lane",
         "People",
         "Pepe Jeans",
         "Peter England",
         "Planet Fashion",
         "Prapti",
         "Priknit",
         "Private Lives",
         "Promod",
         "Provogue",
         "Punk",
         "Quiksilver",
         "RENE",
         "Raymond",
         "Red Tape",
         "Reid & Taylor",
         "Reliance Footprint",
         "Reliance Trends",
         "Ritu Kumar",
         "Roxton",
         "Salvatore Ferragamo",
         "Samsonite",
         "Satya Paul",
         "Scullers",
         "Shoppers Stop",
         "Sisley",
         "Skechers",
         "Splash",
         "Spykar",
         "Stanmax",
         "Suvasa",
         "Tantra",
         "The Collective",
         "Thomas Pink",
         "Timberland",
         "Trendy Divva",
         "Tresmode",
         "Triumph",
         "US Polo",
         "Uni Style Image",
         "United Colors of Benetton",
         "VIP Bags",
         "Van Heusen",
         "Vans",
         "Venus Steps",
         "Vero Moda",
         "Vineet's Sarees",
         "W for Women",
         "Wills Lifestyle",
         "Woodland",
         "Woods",
         "ZARA",
         "Zodiac"
      ]
   },
   {
      "id": "corporate-companies",
      "name": "Corporate Companies",
      "childrens": [
         "3ade translation services l",
         "A P Singh & Co Advocates",
         "AIM India Pvt. Ltd.",
         "Abcd E-Examinations",
         "Aggarwal Corporate Tower",
         "Aggarwal Millennium Tower",
         "Aggarwal Plaza",
         "Aipl Business Club",
         "Airtel UNOC",
         "Amazon Development Centre",
         "Ansal Api Esencia",
         "Artha IBM India",
         "Assotech Business Cresterra",
         "Azadpur Commercial Complex",
         "BPTP Office",
         "BT India",
         "Bharti Airtel Ltd",
         "Bt Global Services Pvt Ltd",
         "CPA Global",
         "Capital Cyberscape",
         "Cast You",
         "Ccn Broadband",
         "Charmwood Plaza",
         "Comviva",
         "Concentrix Ggn Bldg14",
         "Coworkinsta",
         "DEEPAK RASTOGI & ASSOCIATES",
         "DLF CYBER PARK",
         "Dabur India Ltd",
         "Delhi IT Park",
         "Denave India Pvt Ltd",
         "Enterslice",
         "Ericsson INDIA Pvt Ltd",
         "Express Trade Tower 2",
         "Galaxy Business Park",
         "Galaxy Consultants",
         "Galleria Tower",
         "Genpact Dlf",
         "Global Business Park",
         "Godrej Office",
         "Hipad INDIA",
         "Home Shop 18",
         "Ifci Tower",
         "Igl Corporate Office",
         "Indian Achievers Forum",
         "Indigo",
         "Infotech Centre",
         "Innov8",
         "Ion Digital Zone",
         "JMD Regent Square",
         "Jindal Intellicom",
         "Mahesh Dayma Corporator",
         "Max Towers",
         "Mira Corporate Suites",
         "Mohit Travels",
         "Mundka Metro Depot",
         "Myupchar",
         "Nearbuy India Pvt Ltd",
         "One Horizon Center",
         "Oracle India Pvt Ltd",
         "Pioneer E Solutions",
         "Pioneer Square",
         "Planet Spark",
         "Prism World Pvt Ltd",
         "Quickcompany",
         "RR Assessment Centre",
         "Rivigo Corporate Office",
         "Rm 22 Facility Solution",
         "SAR Group",
         "SEWA TOWER",
         "Sewa Tower",
         "Siti Cable Network Ltd",
         "Skillhub infotech pvt ltd",
         "Smartworks",
         "Splendor Trade Tower",
         "Square Yards",
         "Sumit Srivastava",
         "Supertech",
         "Technocp Business Solutions",
         "Teleperformance",
         "Travclan",
         "UBER Office",
         "Uber Office",
         "Vestige Head Office",
         "Wazirpur PF Office",
         "Wegmans Industries Pvt Ltd",
         "World Trade Tower",
         "Younity",
         "agarwal packers and movers",
         "ajnara india ltd corporate",
         "amazon development centre",
         "american express banking co",
         "apollo munich health insura",
         "ats infrastructure ltd cor",
         "bajaj capital ltd corporat",
         "bata india ltd head office",
         "bharti enterprises limited",
         "bharti infratel limited he",
         "blazeflash couriers ltd co",
         "bsa citi courier pvt ltd c",
         "cafe coffee day corporate",
         "chaayos corporate office",
         "clix capital services pvt l",
         "collegedekho corporate offi",
         "conduent business services",
         "council for the indian scho",
         "delhi airport metro express",
         "devyani international ltd",
         "emaar mgf land limited cor",
         "ernst young global limite",
         "escorts ltd corporate offi",
         "ferns n petals corporate o",
         "fortis hospital corporate",
         "fortune park hotels ltd co",
         "fresca juices corporate of",
         "gmr group corporate office",
         "gojavas corporate office",
         "gold souk group corporate",
         "google.com corporate offic",
         "grand vivanta vacations pvt",
         "haldiram corporate office",
         "hitachi home life solutio",
         "ht media ltd corporate off",
         "india yamaha motor pvt ltd",
         "indraprastha gas ltd head",
         "itc green center ltd corpo",
         "jabong.com registered co",
         "jaiprakash associates ltd",
         "jbm group corporate office",
         "kaizen training solutions p",
         "lifeasy on demand home se",
         "limeroad.com corporate off",
         "mahagun india pvt ltd corp",
         "maruti suzuki india ltd he",
         "micromax informatics ltd h",
         "motorola solutions corpora",
         "muthoot finance ltd corpor",
         "national payments corporati",
         "neemrana hotels pvt ltd co",
         "net ambit infosource e se",
         "network 18 india ltd corpo",
         "news24 broadcast india ltd",
         "nikon india pvt ltd corpor",
         "noida international univers",
         "noida power company ltd he",
         "omaxe ltd corporate office",
         "oppo mobile head office",
         "optum global solutions indi",
         "orient electric corporate",
         "oxford academy of tuitions",
         "oxigen services india pvt l",
         "oxygen business park pvt lt",
         "p c financial services pvt",
         "philips electronics india l",
         "prateek group corporate of",
         "punjab kesari head office",
         "puri constructions pvt ltd",
         "pvr ltd corporate office",
         "rama group of institutions",
         "sahara india tv network re",
         "shine.com corporate office",
         "snapdeal.com head office",
         "sony india pvt ltd registe",
         "su kam power systems ltd c",
         "sunflame enterprises pvt lt",
         "supertech ltd corporate of",
         "tata consultancy service lt",
         "tata power delhi distributi",
         "the 3c company corporate o",
         "unitech ltd corporate offi",
         "us visa application center",
         "v mart retail limited corp",
         "vatika group corporate off",
         "videocon industries ltd co",
         "vishal mega mart pvt ltd h",
         "vodafone mobile services lt",
         "walmart pvt ltd corporate",
         "wave infratech pvt ltd cor",
         "wellman employment india pv",
         "yes madam beauty services a"
      ]
   },
   {
      "id": "hardware-stores",
      "name": "Hardware Stores",
      "childrens": [
         "A.k.s Networking Solution",
         "Aar Aas Enterprises",
         "Agrawal Hardware",
         "Ahaan Enterprises",
         "Atul Enterprises",
         "B M Ent",
         "Bhati Hardware House",
         "Ganga Enterprises",
         "Genesis Network",
         "Hakimi Paints",
         "Hanuman Hardware",
         "Hanuman Trading Company",
         "Hardware Centre",
         "Industrial Belting Company",
         "Janta Furniture House",
         "Khimasiya Steels",
         "Laxmi Enterprises",
         "Le Pine Wood",
         "M B Traders",
         "Mg System",
         "Mittal Brass Collection",
         "Namoh Hardware",
         "Om Plywood And Glass Center",
         "Perfect Office Equipment",
         "Plywood Wholesaler",
         "Ramdev Kitchen & Hardware",
         "S. S. Hardware & Sanitary",
         "Satarkar Enterprises",
         "Shani Hardware And System",
         "Sohan Lal Gupta & Co",
         "Sri Rajaram Hardware",
         "Star Hardware",
         "Tech Sales & Services",
         "Tirupati Hardware",
         "anupam architectural and ha",
         "bhagyalaxmi hardware and pl",
         "bhavani plywoods hardware",
         "chimandas valiram and compa",
         "priyanshu hardware photo st",
         "shree krishna plywood har",
         "vinayaga tools hydraulic"
      ]
   },
   {
      "id": "home-and-kitchen",
      "name": "Home & Kitchen",
      "childrens": [
         "@home",
         "Asian Paints",
         "Atmosphere",
         "Black & Decker",
         "Boconcept",
         "Bombay Dyeing",
         "Bonita",
         "Evok",
         "Faber",
         "Featherlite Living",
         "Ferns N Petals",
         "Florista",
         "Goodearth",
         "Hindware",
         "Home Centre",
         "HomeStop",
         "HomeTown",
         "Kent",
         "Lladró",
         "Maspar",
         "Nilkamal",
         "Prestige Smart Kitchen",
         "Singer",
         "Sleek",
         "Sobha Restoplus",
         "Sunflame",
         "Tied Ribbons",
         "Tupperware",
         "Westside"
      ]
   },
   {
      "id": "jewellery",
      "name": "Jewellery",
      "childrens": [
         "Anmol Jewellers",
         "Art Karat",
         "Ayesha",
         "Bracialeto",
         "Citizen",
         "Cygnus",
         "Diacolor",
         "Ethos Watches",
         "Fossil",
         "GC Smart Luxury",
         "Ganjam",
         "Gili",
         "Gitanjali Jewels",
         "GordonMax",
         "Harry Winston",
         "Helios",
         "Johnson Watch",
         "Joyalukkas",
         "Kalyan Jewellers",
         "Kapoor Watch",
         "Karigari",
         "Lalique",
         "Malabar Gold and Diamonds",
         "Maya Jewels",
         "Momentz",
         "Nakshatra",
         "Omega",
         "Orra",
         "Piaget",
         "Rado Switzerland",
         "Reliance Jewels",
         "Rolex",
         "Rose",
         "Seiko",
         "Sonata Watches",
         "Swarovski",
         "Swatch",
         "Tag Heuer",
         "Tanishq",
         "Tara Jewellers",
         "The Gem Palace",
         "Timex",
         "Tissot",
         "Titan",
         "Vacheron Constantin"
      ]
   },
   {
      "id": "mobiles-and-electronics",
      "name": "Mobiles & Electronics",
      "childrens": [
         "Acer",
         "Airtel",
         "Apple",
         "Asus",
         "Baltra",
         "Bang & Olufsen",
         "Bose",
         "Brother",
         "Camarena",
         "Canon",
         "Casio",
         "Croma",
         "Dell",
         "Ezone",
         "Game4U",
         "Godrej",
         "HP",
         "IFB",
         "IStore",
         "Idea Cellular",
         "Imagine",
         "Intex",
         "Khaitan",
         "LG",
         "Lenovo",
         "Micromax",
         "Nikon",
         "Nokia",
         "OSIM",
         "Onida",
         "Panasonic",
         "Philips",
         "Planet M",
         "Reliance Digital",
         "Reliance Digital Express",
         "Samsung",
         "Sangeetha Mobile",
         "Sony Centre",
         "Spice Hotspot",
         "Swipe Telecom",
         "Tata Docomo",
         "Telenor",
         "Toshiba",
         "Vertu",
         "Videocon",
         "Vijay Sales",
         "Vodafone",
         "Xolo"
      ]
   },
   {
      "id": "restaurants",
      "name": "Restaurants",
      "childrens": [
         "Barbeque Nation",
         "Barista",
         "Baskin Robbins",
         "Booster Juice",
         "Burger King",
         "Cafe Coffee Day",
         "Candy Treats",
         "Chi Kitchen & Bar",
         "Chicago Pizza",
         "Chili's",
         "Choko la",
         "Chá shi",
         "Club City",
         "Cocoberry",
         "Cookie Man",
         "Costa Coffee",
         "Cream Bell",
         "Domino's Pizza",
         "Dunkin' Donuts",
         "Gelato Vinto",
         "Geoffrey's",
         "Gloria Jeans Coffees",
         "Go Chaatzz",
         "Goli Vada Pav",
         "Haldiram's",
         "Hard Rock Cafe",
         "Hokey Pokey",
         "Juice Lounge",
         "KFC",
         "Kaatizone",
         "Kobe Sizzlers",
         "Kwality Walls",
         "Let's Noodle",
         "Mad Over Donuts",
         "Mamagoto",
         "McDonald's",
         "Moti Mahal",
         "Nando's",
         "New York Pizza & Fried Chicken",
         "Nirula's",
         "Papa Johns",
         "Pind Balluchi",
         "Pino's Pizza",
         "Pizza Express",
         "Pizza Hut",
         "Punjab Grill",
         "Rajdhani Thali",
         "Red Mango",
         "Saravana Bhavan",
         "Sbarro",
         "Spaghetti Kitchen",
         "Starbucks",
         "Subway",
         "TGI Friday's",
         "The Beer Café",
         "The Coffee Bean & Tea Leaf",
         "The Yellow Chilli",
         "YogurBerry"
      ]
   },
   {
      "id": "shopping-mall",
      "name": "Shopping Mall",
      "childrens": [
         "Aditya Mega City",
         "Agarwal City Mall",
         "Aggarwal Prestige Mall",
         "Ambience Mall Gurgaon",
         "Ambience Mall Vasant Kunj",
         "Ansal Plaza Delhi",
         "Ansal Plaza Noida",
         "Ansal Plaza Vaishali",
         "Capital Mall Bhiwadi",
         "Center Stage Mall",
         "Choudhary Mall",
         "City Centre Rohini",
         "City Square Mall Rajouri Garden",
         "Cross River Mall",
         "Crown Interiorz Mall",
         "Crown Plaza",
         "D Mall Rohini",
         "DLF City Centre Gurgaon",
         "DLF City Centre Shalimar Bagh",
         "DLF Emporio",
         "DLF Galleria",
         "DLF Mega Mall",
         "DLF Place Saket",
         "DLF Promenade",
         "DLF Star Mall",
         "East Delhi Mall",
         "Eros Metro Mall",
         "Gaur Central Mall",
         "Gold Souk Gurgaon",
         "Jaipuria Sunrise Plaza Mall",
         "Krishna Mall",
         "MGF Mega City Gurgaon",
         "MGF Metropolitan Gurgaon",
         "MGF Metropolitan Mall Saket",
         "MMX Mall",
         "Mahagun Metro Mall",
         "Metro Walk Mall",
         "Moments Mall",
         "North Square Mall",
         "Pacific Mall Delhi",
         "Pacific Mall Ghaziabad",
         "Parsvanath City Mall",
         "Pinnacle Mall Dwarka",
         "Raheja Mall",
         "Ramada Mall",
         "Ring Road Mall",
         "SAB Mall",
         "Sahara Mall",
         "Select Citywalk",
         "Shipra Mall",
         "Shoprix Mall",
         "Spice Mall",
         "Star City Mall",
         "The Crescent at Qutab",
         "The Great India Place",
         "The Opulent",
         "V Square Mall",
         "V3S Mall",
         "Vikas Surya Shopping Mall",
         "West Gate Mall"
      ]
   },
 ];